# Generated by Django 5.0.4 on 2024-06-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='color',
            field=models.CharField(choices=[('green', 'Verde'), ('blue', 'Azul'), ('red', 'Vermelho'), ('yellow', 'Amarelo'), ('purple', 'Roxo')], max_length=6),
        ),
    ]
