# Generated by Django 5.0.4 on 2024-07-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_color'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wallet',
            table='Wallets',
        ),
    ]
